[package]
name = "prompty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
reqwest = "0.11.13"
poise = "0.5.2"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
serde = "1.0"
serde_json = "1.0"
