# fly.toml app configuration file generated for prompty on 2023-04-23T16:26:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "prompty"
primary_region = "iad"

[env]
RUST_LOG = "INFO"
